server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /abl
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB

  jmx:
    enabled: false
  datasource:
    name: huazhi
    type: com.alibaba.druid.pool.DruidDataSource
    #druid配置
    druid:
      #监控统计拦截器
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://192.168.0.178:3306/project_managerment?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      url: jdbc:mysql://192.168.0.178:3306/xiaoji_project_managerment?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 1234
#      password: 1234
      #配置初始化大小/最大/最小
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接数
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小，oracle设未true，mysql设未false，分库分表比较推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  #异常处理
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
  resources:
    add-mappings: false
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaoji.duan.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

zuul:
  authorize:
    url: http://sa-aba:8080/aba/user
    path:
  groupuser:
    url: http://sa-abd:8080/abd/my
    path:
